### ISSUE TITLE
How to change current track and make controls reflect the change

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ionic-audio#1]
## Observations
Each <track> element has its own player instance. So we would have to use a simple list and only ONE instance of the player on the bottom of the page?

## TODO
- [x] Figure out why changes aren't reflected.
- [x] Whenever the track is changed, UI doesn't reflect the change
- [x] Progress bar doesn't show time for updated current track
- [ ] Build previousTrack() / nextTrack() methods

## Docs
- https://www.google.ca/search?q=ngdocheck+angular2&oq=ngdocheck+angular2
- https://juristr.com/blog/2016/04/angular2-change-detection/

## Refs
- https://github.com/arielfaur/ionic-audio/issues/106
- https://github.com/arielfaur/ionic-audio/issues/66#issuecomment-250599740
- https://github.com/arielfaur/ionic-audio/issues/108
