### ISSUE TITLE
How to manage & access playlist?

### ISSUE THREAD

**Issue by tbergeron** [tbergeron/ionic-audio#2]
There should be addTrack / removeTrack / clearTracks kind of methods.

## TODO
- `add()`, `remove()`
    - add https://github.com/tbergeron/ionic-audio/blob/3.0/dist/ionic-audio-providers.ts#L54
    - [x] add remove method https://github.com/tbergeron/ionic-audio/blob/cdf6c3f0679d6a09bc69df3c937294fd0d434a95/dist/ionic-audio-providers.ts#L64
- `tracks()`
    - tracks() https://github.com/tbergeron/ionic-audio/blob/3.0/dist/ionic-audio-providers.ts#L102
- `current()`
    - `current()` https://github.com/tbergeron/ionic-audio/blob/3.0/dist/ionic-audio-providers.ts#L112
- `current(id)` (set)
    - `current(id)` https://github.com/tbergeron/ionic-audio/blob/3.0/dist/ionic-audio-providers.ts#L121
- [x] `clear()` https://github.com/tbergeron/ionic-audio/blob/cdf6c3f0679d6a09bc69df3c937294fd0d434a95/dist/ionic-audio-providers.ts#L77
- [x] Tweak demo to test changes
- [x] Test changes
- [x]  PR on original repo?
    - Wait for whole changes
